name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          repository: openstack/barbican
          ref: d4365b8abffaa05b0c6873b7ff503e089a61bdfa # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          image-name: barbican
          build-contexts: barbican=openstack/barbican
          push: ${{ github.event_name != 'pull_request' }}
