name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@286455d3dcce221b89a5b9cfb836ef2ee4f7df69 # main
        with:
          repository: openstack/barbican
          ref: 680af26ae2360c433fad9bf5d82c63480af68a16 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@286455d3dcce221b89a5b9cfb836ef2ee4f7df69 # main
        with:
          image-name: barbican
          build-contexts: barbican=openstack/barbican
          push: ${{ github.event_name != 'pull_request' }}
